/**
 * The Homebrew cask for mvpfy, as text.
 *
 * Homebrew's own cask repository will not take mvpfy yet: it refuses
 * pre-release versions outright, and asks for a notability its repository does
 * not have. So the cask lives in a tap of our own, where neither rule applies,
 * and this renders it from a release rather than anyone editing Ruby by hand
 * once per version and getting a checksum wrong.
 */
export const CASK_TOKEN = 'mvpfy';
export const APP_BUNDLE = 'mvpfy by feature1.app';
const REPO = 'feature1-ai/mvpfy.ai';

/**
 * @param {{ version: string, sha256: string }} release - `version` without its
 *   leading v ("1.0.0-beta.18"), `sha256` of the .dmg GitHub published.
 * @returns {string}
 */
export function renderCask({ version, sha256 }) {
  if (!/^\d+\.\d+\.\d+(-[\w.]+)?$/.test(version)) {
    throw new Error(`Not a version: "${version}" — expected 1.0.0 or 1.0.0-beta.18`);
  }
  if (!/^[0-9a-f]{64}$/.test(sha256)) {
    throw new Error('sha256 must be 64 lowercase hex characters');
  }
  return `# Generated by packaging/cask.mjs — do not edit by hand.
cask "${CASK_TOKEN}" do
  version "${version}"
  sha256 "${sha256}"

  url "https://github.com/${REPO}/releases/download/v#{version}/mvpfy-by-feature1-#{version}.dmg",
      verified: "github.com/${REPO}/"
  name "mvpfy by feature1"
  desc "The IDE for PMs — plan a feature, implement it, ship the pull request"
  homepage "https://github.com/${REPO}"

  # The releases are pre-releases, which the default GitHub strategy skips.
  livecheck do
    url :url
    strategy :github_releases
    regex(/^v?(\\d+(?:\\.\\d+)+(?:-[\\w.]+)?)$/i)
  end

  depends_on macos: ">= :big_sur"

  app "${APP_BUNDLE}"

  # Nothing here clears the quarantine flag. These builds are unsigned, so
  # macOS will refuse the first launch, and a cask could strip that flag in a
  # postflight — but disabling Gatekeeper on someone's behalf, as a side effect
  # of an install they thought was routine, is not ours to decide. The install
  # instructions offer --no-quarantine so it stays the user's own choice.

  # Deliberately not ~/.mvpfy: that is where projects, worktrees and their
  # uncommitted work live. Uninstalling the app must not be able to delete
  # someone's code, even when they asked for everything to go.
  zap trash: [
    "~/Library/Application Support/mvpfy by feature1",
    "~/Library/Caches/ai.feature1.mvpfy",
    "~/Library/Caches/ai.feature1.mvpfy.ShipIt",
    "~/Library/Preferences/ai.feature1.mvpfy.plist",
    "~/Library/Saved Application State/ai.feature1.mvpfy.savedState",
  ]
end
`;
}
